### PR TITLE
BUGFIX: Cache transformed links

### LINKED ISSUE #3: Replaced links are not cached
On cached pages the links are mailto links not email2powermail links.

In my opinion 

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-output']`

should be changed to

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-all']`

### PR DESCRIPTION
**Pull request by christophlehmann**
Closes #3

### CODE REVIEW

**Comment by einpraegsam** [comment]
As far as I remember: In the good old TYPO3 days there where two hooks for fe-manipulation. One for pages with and another for pages without cache. Does your patch work in both cases?

**Comment by christophlehmann** [comment]
Yes, `contentPostProc-all` is the hook for post-processing of page content cached/non-cached

**Comment by christophlehmann** [comment]
Ah, now i see the difference between them. _INT-Objects are not transformed with `contentPostProc-all` so we need both

**Comment by einpraegsam** [comment]
Ok, can you update your pull request to use both methods?

**Pull request closed without merging**
